#+LATEX_HEADER:  \usepackage{bibentry}
#+LATEX_HEADER:  \nobibliography*
#+LATEX_HEADER:  \usepackage{titlesec}
#+LATEX_HEADER:  \titleformat{\chapter}[display]
#+LATEX_HEADER:    {\normalfont\sffamily\huge\bfseries\color{blue}}
#+LATEX_HEADER:    {\chaptertitlename\ \thechapter}{20pt}{\normalsize} \titleformat{\section}
#+LATEX_HEADER:    {\normalfont\sffamily\large\bfseries\color{Black}}
#+LATEX_HEADER:    {\thesection}{1em}{}



#+BEGIN_SRC latex :exports results :results output
\begin{center}
--------------------------------------------------------------------------------------------------------------------------

\textbf{\Large MACS 30301 - Introduction to Bayesian Statistics}

Computational Social Science

Division of the Social Sciences

University of Chicago

Autumn/2019

--------------------------------------------------------------------------------------------------------------------------
\end{center}
#+END_SRC

* Course information
:PROPERTIES:
:UNNUMBERED: t
:END:

#+ATTR_LaTeX: :center nil :align rl
| *Instructor:*   | [[https://.diogoferrari.com][Diogo Ferrari]]                          |
| *e-mail:*       | [[mailto:diogoferrari@uchicago.edu][diogoferrari@uchicago.edu]]              |
| *Office:*       | 5730 S. Woodlawn, Room 406             |
| *Office-hours:* | Monday 15:00-17:00 (or by appointment) |
|                 |                                        |
|                 |                                        |
| *TA:*           | TBA                                    |


- *Meeting day/time*  MWF 10:30-11:20 

* Description
:PROPERTIES:
:UNNUMBERED: t
:END:

The goal of this course is to give students an overview of the theory and methods for data analyses using the Bayesian paradigm. Topics include: (1) foundations of Bayesian inference; (2) development of Bayesian models and prior choices; (3) analytical and simulation techniques for posterior estimation; (4) model choice and diagnostics; (5) sensitivity analysis, and; (6) introduction to Monte Carlo Markov Chain (MCMC) simulations. Students will also learn how to estimate and summarize Bayesian models using Bayesian statistical packages (R/JAGS/Bugs). The course will use working examples with real application of Bayesian analysis in social sciences. Prerequisites: Basic knowledge of probability (e.g., joint and conditional distributions, expectation, variance) and introductory-level experience with R or Python (Note: Open to Advanced Undergraduates with Instructor Permission)
* Evaluation
:PROPERTIES:
:UNNUMBERED: t
:END:

#+ATTR_LaTeX: :center nil :align |r|c|c|
|--------------+-------+--------------|
|              | Total | Total weight |
|--------------+-------+--------------|
| Problem sets |     8 |          80% |
| Final exam   |     1 |          20% |
|--------------+-------+--------------|

* Disability Service and Accomodation
:PROPERTIES:
:UNNUMBERED: t
:END:
If you need any special accommodations, please provide your instructor with a copy of your Accommodation Determination Letter (provided to you by the Student Disability Services office) as soon as possible so that you may discuss with him/her how your accommodations may be implemented in this course.
* Schedule  
:PROPERTIES:
:UNNUMBERED: t
:END:
*** Calendar
#+ATTR_LATEX: :align |c|c|l|p{9cm}|l| :font \footnotesize
|----+------+-----+-----------------------+---------------------|
|  # | Week | Day | Topic                 | Assignment          |
|----+------+-----+-----------------------+---------------------|
|  1 |    1 |     | The Bayesian Paradigm |                     |
|  2 |    1 |     |                       |                     |
|  3 |    1 |     |                       | PS1 (ho)            |
|----+------+-----+-----------------------+---------------------|
|  4 |    2 |     |                       |                     |
|  5 |    2 |     |                       |                     |
|  6 |    2 |     |                       | PS2 (ho); *PS1 (d)* |
|----+------+-----+-----------------------+---------------------|
|  7 |    3 |     |                       |                     |
|  8 |    3 |     |                       |                     |
|  9 |    3 |     |                       | PS3 (ho); *PS2 (d)* |
|----+------+-----+-----------------------+---------------------|
| 10 |    4 |     |                       |                     |
| 11 |    4 |     |                       |                     |
| 12 |    4 |     |                       | PS4 (ho); *PS3 (d)* |
|----+------+-----+-----------------------+---------------------|
| 13 |    5 |     |                       |                     |
| 14 |    5 |     |                       |                     |
| 15 |    5 |     |                       | PS5 (ho); *PS4 (d)* |
|----+------+-----+-----------------------+---------------------|
| 16 |    6 |     |                       |                     |
| 17 |    6 |     |                       |                     |
| 18 |    6 |     |                       | PS6 (ho); *PS5 (d)* |
|----+------+-----+-----------------------+---------------------|
| 19 |    7 |     |                       |                     |
| 20 |    7 |     |                       |                     |
| 21 |    7 |     |                       | PS7 (ho); *PS6 (d)* |
|----+------+-----+-----------------------+---------------------|
| 22 |    8 |     |                       |                     |
| 23 |    8 |     |                       |                     |
| 24 |    8 |     |                       | PS8 (ho); *PS7 (d)* |
|----+------+-----+-----------------------+---------------------|
| 25 |    9 |     |                       |                     |
| 26 |    9 |     |                       |                     |
| 27 |    9 |     |                       | *PS8 (d)*           |
|----+------+-----+-----------------------+---------------------|
| 28 |   10 |     |                       |                     |
| 29 |   10 |     |                       |                     |
| 30 |   10 |     |                       | *Final Exam*        |
|----+------+-----+-----------------------+---------------------|
- ho: hand out
- d: due date
*** Scheduled readings

* Textbooks
:PROPERTIES:
:UNNUMBERED: t
:END:
*** Required
- Gill, J. (2014) Bayesian methods: a social and behavioral sciences approach: CRC press.\\
  /Practical introduction of the concepts of Bayesian statistics with examples of application in social sciences./

*** Recommended
- Gelman, A., Carlin, J. B., Stern, H. S., & Rubin, D. B.  (2014) Bayesian Data Analysis, Chapman & Hall/CRC Boca Raton, FL, USA.\\
  /Called for many people "The Bible", this book contains a comprehensive overview of many topics in Bayesian statistics./
- Jackman, S. (2009)  Bayesian analysis for the social sciences , John Wiley & Sons.\\
  /The book contains more advanced treatment of some topics in Bayesian analysis./
- Kruschke, J. (2015) Doing bayesian data analysis: a tutorial with r, jags, and stan, Academic Press.\\
  /This is an introduction-level book with many examples and illustrations of Bayesian analysis. It covers the computational side, and it is a useful tutorial-like approach for practical implementation of Bayesian models in JAGS./

* Software
:PROPERTIES:
:UNNUMBERED: t
:END:
- Team, R. C. (2018) R: a language and environment for statistical computing.\\
  /Free statistical software available for download at [[https://www.r-project.org/][this]] website. The software is available for all main operation system (Linux, OS, Windows)/
- Plummer, M., Stukalov, A., & Denwood, M. (2018) Rjags: r api to jags.\\
  /Free software for Bayesian analysis available for download at [[https://sourceforge.net/projects/mcmc-jags/files/][this]] website. The software is available for UNIX based operation system (Linux, OS)./
- Lunn, D., Jackson, C., Best, N., Thomas, A., & Spiegelhalter, D. (2012) The bugs book: a practical introduction to bayesian analysis, CRC press.\\
  /Windows users can install the free windows based version called WinBUGS instead of JAGS, which is available for download at [[https://www.mrc-bsu.cam.ac.uk/software/bugs/the-bugs-project-winbugs/][this]] website/
- Plummer, M. (2017) Jags version 4.3.0 user manual.\\
  /R package used to estimate Bayesian models using JAGS./
* Academic Integrity
:PROPERTIES:
:UNNUMBERED: t
:END:

The University of Chicago has a [[https://studentmanual.sites.uchicago.edu/Policies#Honesty][formal policy on academic honesty]] that you are expected to adhere to. Here are some guidelines we expect you to follow:
1. Courtesy, honesty, and respect should be shown by students toward faculty members, guest lecturers, administrative support staff, and fellow students. Similarly, students should expect faculty to treat them fairly, showing respect for their ideas and opinions and striving to help them achieve maximum benefits from their experience in the School.
2. Academic dishonesty can encompass many activities, which includes plagiarism, cheating, fabrication, falsification of records or official documents, intentional misuse of equipment or materials (including library materials), and aiding and abetting the perpetration of such acts. One of the gravest academic dishonesty is plagiarism: knowingly handing in someone else's work as your own, whether it be work done by another student in the class or available publicly on the Internet. This class has a zero tolerance policy for plagiarism.
3. The preparation of solutions for problem sets, papers, and examinations, assigned on an individual basis, must represent each students own effort. Therefore:
   - You MUST NOT copy or use someone else's work (with or without their permission) in your own solution. You have to write your own.
   - DO NOT post your solutions to problem sets or exams in publicly-accessible websites, like pastebin, a public GitHub repository, GitHub gists, etc. While these tools may seem like convenient mechanisms for sharing code with an instructor/TA or with a project partner, they can also expose your code to other students in the class. If you do post your solution in a publicly-accessible location, and we find out about it outside of a plagiarism incident, you will just get a warning. However, if another student in the class uses code that you posted on such a site (even if you did not intend for that code to be used by someone else), you be considered an equally guilty party in a plagiarism offense, and will receive the exact same penalty as the student who used your code.



